{{- if .Values.filebeat.enabled -}}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: {{ .Values.namespace }}
spec:
  type: filebeat
  version: {{ .Values.version }}
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    filebeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints:
            enabled: true
    setup.ilm.enabled: true
    setup.ilm.policy_name: "custom-ilm"
    setup.ilm.policy_file: "/usr/share/filebeat/ilm-policy.json"
    setup.ilm.check_exists: true
    setup.ilm.overwrite: true
    setup.template.settings:
      index.number_of_shards: 2
      index.number_of_replicas: 1
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    - drop_fields:
        fields:
        - agent
        - ecs
        - host
    logging.metrics.enabled: false
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        priorityClassName: filebeat-pod-critical
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          {{- with .Values.filebeat.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: ilm-configmap-volume
            mountPath: /usr/share/filebeat/ilm-policy.json
            subPath: ilm-policy.json
            readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: ilm-configmap-volume
          configMap:
            name: ilmpolicy-config
{{- end}}
