{{- if .Values.filebeat.enabled -}}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: {{ .Values.namespace }}
spec:
  type: filebeat
  version: {{ .Values.version }}
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    filebeat.autodiscover:
      providers:
      - type: kubernetes
        node: ${NODE_NAME}
        hints:
          enabled: true
    setup.ilm.enabled: true
    setup.ilm.policy_name: "custom-ilm"
    setup.ilm.policy_file: "/usr/share/filebeat/ilm-policy.json"
    setup.ilm.check_exists: true
    setup.ilm.overwrite: true
    setup.template.settings:
      index.number_of_shards: 2
      index.number_of_replicas: 1
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    - drop_fields:
        fields:
        - agent
        - ecs
        - host
    logging.metrics.enabled: false
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        priorityClassName: filebeat-pod-critical
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30    
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          {{- with .Values.filebeat.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: ilm-configmap-volume
            mountPath: /usr/share/filebeat/ilm-policy.json
            subPath: ilm-policy.json
            readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: ilm-configmap-volume
          configMap:
            name: ilmpolicy-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ .Values.namespace }}
{{- end}}
